server {
    listen 80;
    server_name localhost;

    # Regra 1: Serve os arquivos do Front-end (HTML, JS, CSS)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Regra 2: PROXY REVERSO - Tudo que começar com /api vai para o Back-end
    location /api/ {
        proxy_pass $BACKEND_URL; # IP público e porta do producer
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
