name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

# Concede superpoderes de escrita para o robô conseguir criar a página web pública
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # ==========================================
  # FASE 1: CI - Validação e Auditoria Estática
  # ==========================================
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Validate Web Assets Syntax
        run: |
          echo "=== INITIALIZING STATIC ANALYSIS FOR VANILLA ENTERPRISE ==="
          (test -f index.html || test -f index.html.gz) && echo "Success: HTML structure is present." || (echo "Error: HTML assets missing!" && exit 1)
          test -f app.js && echo "Success: app.js is present." || (echo "Error: app.js missing!" && exit 1)

      # Passo extra: Empacota os arquivos validados da pasta para a esteira de deploy
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  # ==========================================
  # FASE 2: CD - Deploy Automatizado (Production)
  # ==========================================
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-validate #  REGRA : O CD só liga se o CI passar 100% verde!
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
