name: "Invoice Frontend - [CD] Deploy"

on:
#  push:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }} # Certifique-se de ter essa secret ou mude para o seu usuário do docker
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/invoice-frontend:$IMAGE_TAG .
          docker push ${{ vars.DOCKER_USERNAME }}/invoice-frontend:$IMAGE_TAG
      #  Transfere o arquivo de deploy para a VM via SCP
      - name: Copy deployment script to OCI VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_CLOUD_IP }}
          username: opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "scripts/deploy-docker.sh"
          target: "/home/opc/projetos/invoice-frontend/scripts" # Pasta exclusiva do front-end
          strip_components: 1
      - name: Executar Deploy na VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ github.sha }}  # Captura o hash do commit
        with:
          host: ${{ secrets.ORACLE_CLOUD_IP }}
          username: opc
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_TAG
          script_stop: true
          script: |
            chmod +x /home/opc/projetos/invoice-frontend/scripts/deploy-docker.sh
            export IMAGE_TAG=$IMAGE_TAG
            # Executa o script de deploy run
            /home/opc/projetos/invoice-frontend/scripts/deploy-docker.sh "${{ vars.DOCKER_USERNAME }}" "${{ secrets.DOCKER_PASSWORD }}" "${{ secrets.ORACLE_CLOUD_IP }}"

